name = "StackPointers"
uuid = "062a3e2c-34b1-4659-9cae-7af421e0d832"
authors = ["Chris Elrod <elrodc@gmail.com>"]
version = "0.1.0"

[deps]
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
VectorizationBase = "0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
